default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
default_stages:
  - commit
  - push

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: debug-statements
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: detect-private-key

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.14.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=22.10]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        types: [text]
        exclude: ^poetry.lock$
        args: ["--write-changes", "--ignore-words-list", "asend"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: style-format
        name: style-format
        stages: [commit]
        language: system
        pass_filenames: false
        entry: inv style.format
        types: [python]

      - id: style-check
        name: style-check
        stages: [push]
        language: system
        pass_filenames: false
        entry: inv style
        types: [python]

      - id: security-check
        name: security-check
        stages: [push]
        language: system
        pass_filenames: false
        entry: inv secure
        types: [python]

      - id: test
        name: test
        stages: [push]
        language: system
        pass_filenames: false
        entry: inv test
        types: [python]
