site_name: 巴哈姆特動畫瘋 - 歷史資料
site_url: !ENV [SITE_URL, https://lee-w.github.io/bahamut_ani_stat/]
nav:
  - Home: README.md
  - Contributing: contributing.md
  - Plots: plots.md
theme:
  name: "material"
repo_url: https://github.com/Lee-W/bahamut_ani_stat
remote_branch: gh-pages
remote_name: origin
