"""empty message

Revision ID: 3f8f915f67bf
Revises: 
Create Date: 2021-10-21 18:12:26.798805

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3f8f915f67bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_feature')
    op.add_column('anime_score', sa.Column('five_star_percentage', sa.Float(), nullable=True))
    op.add_column('anime_score', sa.Column('four_star_percentage', sa.Float(), nullable=True))
    op.add_column('anime_score', sa.Column('three_star_percentage', sa.Float(), nullable=True))
    op.add_column('anime_score', sa.Column('two_star_percentage', sa.Float(), nullable=True))
    op.add_column('anime_score', sa.Column('one_star_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_score', 'one_star_percentage')
    op.drop_column('anime_score', 'two_star_percentage')
    op.drop_column('anime_score', 'three_star_percentage')
    op.drop_column('anime_score', 'four_star_percentage')
    op.drop_column('anime_score', 'five_star_percentage')
    op.create_table('anime_feature',
    sa.Column('id_', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('ratio', sa.FLOAT(), nullable=True),
    sa.Column('score_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['anime_score.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###
