name: "Publish plots to GitHub Page"

on:
  push:
    branches:
    - 'accumulate-data'
  workflow_dispatch:

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: uv sync --group dev --group doc

      - name: Build docs
        run: uv run poe doc-build-ci

      - name: Push documentation to Github Page
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
